// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvpboolwadliaeqtwpdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2cGJvb2x3YWRsaWFlcXR3cGR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMzY5MTMsImV4cCI6MjA2MDYxMjkxM30.T8V1AoPA3FP0SREJiud3kpOnoML2SOXpXH7wViao3s0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);